version: '3.8'

services:
  chunking_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chunking_container
    ports:
      - "11434:11434"
    volumes:
      - ./know_how:/app/know_how
      - ./db:/app/db
      - ./models:/app/models
    tty: true
    stdin_open: true